
[functions.notificacao-n8n]
enabled = true
verify_jwt = true
import_map = "./functions/notificacao-n8n/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notificacao-n8n/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notificacao-n8n/*.html" ]

[functions.admin-create-user]
enabled = true
verify_jwt = true
import_map = "./functions/admin-create-user/deno.json"
entrypoint = "./functions/admin-create-user/index.ts"
